#!/usr/bin/env bash
set -e

run() {
    PGHOST=localhost PGUSER=doer \
        "$(dirname "$0")/../../scripts/setup/terminate-psql-sessions" doer_test doer_test_base doer_test_template
    psql -v ON_ERROR_STOP=1 -h localhost postgres doer_test <<EOF
DROP DATABASE IF EXISTS doer_test;
CREATE DATABASE doer_test TEMPLATE doer_test_template;
EOF
    "$(dirname "$0")/../../scripts/setup/flush-memcached"
}

run
