#!/usr/bin/env bash
# This tests installing the pgroonga extension
set -e
set -x

crudini --set /etc/zulip/doer.conf machine pgroonga enabled
/home/zulip/deployments/current/scripts/doer-puppet-apply -f
echo 'USING_PGROONGA = True' >>/etc/zulip/settings.py
su doer -c '/home/zulip/deployments/current/manage.py migrate pgroonga'

su doer -c /home/zulip/deployments/current/scripts/restart-server

echo 'Installation of pgroonga complete!'
exit 0
