#!/usr/bin/env bash
set -e
set -x

export DJANGO_SETTINGS_MODULE=zproject.test_settings

create_doer_test() {
    psql -v ON_ERROR_STOP=1 -h localhost postgres doer_test <<EOF
DROP DATABASE IF EXISTS doer_test;
CREATE DATABASE doer_test TEMPLATE doer_test_base;
EOF
}

create_doer_test_template() {
    psql -v ON_ERROR_STOP=1 -h localhost postgres doer_test <<EOF
DROP DATABASE IF EXISTS doer_test_template;
CREATE DATABASE doer_test_template TEMPLATE doer_test;
EOF
}

mkdir -p zerver/tests/fixtures

PGHOST=localhost PGUSER=doer \
    "$(dirname "$0")/../scripts/setup/terminate-psql-sessions" doer_test doer_test_base doer_test_template

create_doer_test

"$(dirname "$0")/../scripts/setup/flush-memcached"

./manage.py migrate --noinput
./manage.py get_migration_status --output="migration_status_test"

# This next line can be simplified to "-n0" once we fix our app (and tests) with 0 messages.
./manage.py populate_db --test-suite -n30 --threads=1 \
    --max-topics=3 \
    --direct-message-groups=0 --personals=0 --percent-direct-message-groups=0 --percent-personals=0

./manage.py dumpdata \
    zerver.UserProfile zerver.Stream zerver.Recipient \
    zerver.Subscription zerver.Message zerver.DirectMessageGroup zerver.Realm \
    zerver.UserMessage zerver.Client \
    zerver.DefaultStream >zerver/tests/fixtures/messages.json

# create pristine template database, for fast fixture restoration after tests are run.
create_doer_test_template
